---

- name: Provison Hosts
  hosts: localhost
  gather_facts: False
  
  tasks:
    - name: EC2 Security group for master
      local_action:
        module: ec2_group
        region: "{{ region }}"
        name: "{{ cluster_name }}-master"
        description: "Spark EC2 group"
        rules:
          - proto: all
            group_name: "{{ cluster_name }}-master"
          - proto: all
            group_name: "{{ cluster_name }}-slaves"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 8080
            to_port: 8081
            cidr_ip: "0.0.0.0/0"
        rules_egress:
          - proto: all
            cidr_ip: "0.0.0.0/0"

    - name: EC2 Security group for workers
      local_action:
        module: ec2_group
        region: "{{ region }}"
        name: "{{ cluster_name }}-slaves"
        description: "Spark EC2 group"
        rules:
          - proto: all
            group_name: "{{ cluster_name }}-master"
          - proto: all
            group_name: "{{ cluster_name }}-slaves"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
        rules_egress:
          - proto: all
            cidr_ip: "0.0.0.0/0"
  

    - name: Launch master
      local_action: 
        module: ec2 
        image:          "{{ image }}"         
        instance_type:  "{{ instance_type }}" 
        key_name:       "{{ key_name }}" 
        group:          "{{ cluster_name }}-master"         
        
        #Add 'type' tag to instance and use it to control the number of instances running
        instance_tags:  
          spark-role: "master"
        count_tag:
          spark-role: "master"
        exact_count:    1

        wait:           true 

      register: master


    - name: Add master instance to host group
      add_host:
        hostname={{ item.public_ip }}
        instance_id={{ item.id }}
        public_ip={{ item.public_ip }}
        private_ip={{ item.private_ip }}
        ansible_ssh_user="ubuntu"
        ansible_ssh_private_key_file="{{inventory_dir}}/keys/{{ key_name }}".pem       
        groups=master,ec2_hosts
      with_items: master.tagged_instances


    - name: Launch workers
      local_action:
        module: ec2
        image:          "{{ image }}"         
        instance_type:  "{{ instance_type }}" 
        key_name:       "{{ key_name }}" 
        group:          "{{ cluster_name }}-slaves"

        instance_tags:  
          spark-role: "worker"
        count_tag:      
          spark-role: "worker"
        exact_count:    "{{ worker_count }}"

        wait:           true

      register: workers

    - name: Add worker instance to host group
      add_host:
        hostname={{ item.public_ip }} 
        instance_id={{ item.id }}
        public_ip={{ item.public_ip }}
        private_ip={{ item.private_ip }}        
        groups=workers,ec2_hosts
        ansible_ssh_user="ubuntu"
        ansible_ssh_private_key_file="{{inventory_dir}}/keys/{{ key_name }}".pem       
      with_items: workers.tagged_instances
  
- include: master.yml


# - name: Setup spark on all hosts
#   hosts: ec2_hosts
#   gather_facts: False


# - name: Start spark master
#   hosts: master

#   tasks:
#   - name: start spark master service
#     service: name=spark-master state=started enabled=true
    
# - name: Start spark workers
#   hosts: ec2_hosts

#   tasks:
#   - name: start spark workers service
#     service: name=spark-workers state=started enabled=true
