---

#Playbook to configure cluster master
- name: Impose social constructs and roles on an innocent server
  hosts: ec2_hosts
  roles: 
    - common
    - hadoop
    - spark
  gather_facts: False

  vars:
    env: 
      HADOOP_CONF: /home/ubuntu/hadoop/conf
      HADOOP_PREFIX: /home/ubuntu/hadoop
      JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64/jre/

- name: Setup hadoop master
  hosts: master
  roles: 
    - hadoop_master
  gather_facts: False

  