sudo: false

env:
  global:
    - MAX_HEAP_SIZE="500M"
    - HEAP_NEWSIZE="100M"
    - JVM_OPTS="$env:JVM_OPTS -XX:+UseG1GC"
    - JVM_OPTS="$env:JVM_OPTS -XX:G1RSetUpdatingPauseTimePercent=5"
    - GEOTRELLIS_KRYO_REGREQ="YES"
    - secure: "XAhJXuXqnGlZlU2pGcIQKJ2rF44gIReA0arHwapFII/gR1h+2e6hgqnMXwrZaQa/EvNBaXq7nF3XcTBjrbK+ABeKA/0lOh/7ryIotP0i1YVrca69pSK9BY+Kr1y7ncLMqvoyjBziobOeVZmxbK4RflgUTIO7MKzzb5pNb9SnOK8="
    - secure: "UwH3B4k5Nqt2THYYTY7uRxTPaJXZbK1hHrVsyJjZp/H2uFTYtQTxXpNb9aR7wuHuhLjXwKkq3gEXxEqhfy6V8+ZPbee6MUNvoYe/HhaPjsmTzcVihTBbO9e7g0bIQFc9bzwY15Y1ImshLcDAYvaXwXapy4Z/KadLiBheyqMk8Cs="
    #Scaladocs
    - secure: "FPfJbtXmhyMTh/eh9B/f6JZIv6aw+XZMipYlJsdgMEv+XKzL1tdYbKQv8G4C13lhyBZmOlQAbOhl4mRUBmq0FqG3361Y9SS4o5KfDRkZNErBTb8tveoRgKLkdLPwooAOUmRUeygKmhO4ehdQsMXCZmCk33nDq/ZrNallfnCRdm8="

language: scala

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

scala:
- "2.10.6"
- "2.11.8"

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

services:
   - docker

before_install:
  - docker run -d --net=host -m 1G --memory-swap -1 --env="MAX_HEAP_SIZE=500M" --env="HEAP_NEWSIZE=100M" --env="CASSANDRA_LISTEN_ADDRESS=127.0.0.1" --name dc-cassandra cassandra:latest

before_script:
  - service --status-all
  - free -m -t

script:
  - ./scripts/buildall.sh

notifications:
  email:
    recipients:
      - lossyrob@gmail.com
      - echeipesh@gmail.com
  slack:
    secure: "RPNymWgr5RXN2LpDERitGAP7pckR19znqAlrcuKE46O7saqlenX6ii8ToRHOe1ba0udJO0B1n2R2OzTlw14AkuETyRKX4X8OtVlU/dtfTHfVMbX6+oRPd1g1mfLrLavR5o2ml/KoIvi9QLbNcVHfqoeA+xxW5TJTm9zayRC9d1M="

before_deploy:
  - export GEOTRELLIS_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: geotrellis/geotrellis
      branch: master
      jdk: oraclejdk7
      scala: "2.10.6"

  - provider: script
    script: .travis/deploy-with-scaladocs.sh
    skip_cleanup: true
    on:
      repo: geotrellis/geotrellis
      branch: master
      jdk: oraclejdk7
      scala: "2.11.8"

after_deploy:
  - rm -f "${HOME}/.bintray/.credentials"

after_failure:
  # show memory usage again
  - free -m -t
  # show actions of the OOM killer
  - dmesg
