sudo: false

env:
  global:
    - secure: "NQqZz0rLHSQ4NpfB/sstKsoEsl6jh1qLQpS7c5ePdqyUt6jSm2FRyLXnca+SzxiLRIWIJmdthm8PFSGdv8Fxr+rnsu8oYBSMvoC4RnfFNoq5tIvv4u0dCFUB4jreZQ9kwwZwBE360skzN4x+kb8EfUYgL3MaKhi/q3D01+5bHIxHhsWUAJRoXVahXLYZiuOzNcu1Ge+1/GrZar3YxgAU/NjrxipYo0bo06dDvLDiie+hFj1BWyO/C1NQcNtApScNv4vNeW0KwaMINjEWpIaJq8nCG26DMMXXpQTlJt7QrxR+W8mGiZR/dyru+oB25AQ7xF48VobN/kEt/cUuEK6YLb+ciYhPPNywxL5S97u4tOP26xFM1ppJfqCGEZHyPZWteUOSkw+sX2S04P30vsdmlsZQBqguJyyB9JkFEkGHFvkaEQTuHw2H/o7rARHEoAnalpa4WBS4myEY3f4vMDUw9jec43EUb2VTTdvBSs1UAuaDtF7rCrz9PuVFvmzZOIvp+HR+8G7q33KiSR+/q98lov20LlxEYXheyCxPgjJVZKDtDYvQQBrtYFfR8n8MZmecFZouBdnnZToGYNioqyfreOqMqm/hYJogpeEgMBztwaGDMwBNYsn7vzTirWpngiyaI21YUcdDZRDpGZb2YzcRthGOWL/vdCeIGuvzlzQmG+4="
    - secure: "H0ffsMpFgxGngHExYiWhEXC7NBTqq3HnL1rlrtk0XMQR/d7HGtYwwTC6aPO0xZSu9zoxpUt83pIpCD/pDQyV3RpfSBIqIeNAsm3rDsSdmBRmhHYtOfIzqv8eCiWIbZLx3UyEkmH0i7mCCWYpYOjvP8PvkUK0UOR1lvnhwYeep1NjGhn7fnJqD/YAxw2SztepJe1yO8oaKSY6OminEyF8P35D2sbJ4zoxeWY1FlBf+sOwPIPDqCMbEs5pTq7CjjFnsRnk0KYC0l4I/goA7nDcPfGnbQBcAOsNmjpCtkqIU0OZpBa5mGL5N+W6QWGP5XHaTva1aiWlAsI1oj+aUxiJQUmPXNvw+ch6dzKiZx3UxADqx7CTnbofe4CIKCpPDt7E88tCXX8i4deZznlWoWAk3PPqEsUbx/MaxVlmos/xoHFlHrnYPMNZHbcP/IJybhtAjCBOKPOWQk+6nZMKKYQg2LqFQII6SWu8PkJgoNCFb91L5Lb7y2CwpZPEpxatn9jaCKmmYQal/ZOmjbr99UdSSknJSB3cULvteUaYlEJw4wP/cxzn57zxf2NSOstKjZBl7Jw2TZ4LvgIt4RUqAeFGgn14Sshdscsh7BQYwv9d0eu2o3nIe6RO43ZIc9/oSftNFV3gg0xJGWH5M8Tv3ht5DF33/zy/7eCzToEfewzkB+M="

language: scala

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

scala:
- "2.10.4"
- "2.11.5"

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

script:
  - ./buildall.sh

notifications:
  email:
    recipients:
      - lossyrob@gmail.com
      - echeipesh@gmail.com
  slack:
    secure: cSn+Ftgb+pyVo9/c/T0NT/aO1YXtrFA9ximJRrl5/W3ZW9OAK6CtaOl5ESyfMrZu5xrNSDZW6guTAID7nYxhT4qCLhvBKFL/KK3OFu2oCZOmeFJTubPcKKu5CyhVAWEbOIEG+XIJPNlQeAWKTMBPVJ2W8Q3O1nIrUdOt0ZCbDqnVr+HCoTtaJAwaJ93fqL0uTACjFUWvOljvvEV4NpInominZpr+Iudb+DtK5vJnxhepkIIsQK/zDdVCBNZ1E+7woPSmUTG7AF3PNDZvUCkfqrFvV6BrKynyRYDnzeDF53DypSVUu65qLLyHazbvKKnTxnmd0jcJP54yLAoK870UDa+prJ6F8bkCHtBR9yAs+nBBM08MwLnKMelt9CGsFluB168p3F6hggDnJbpmX1I5JGiH1ZbDhcdK4cCljfRL4PtoVV4SMye+6E0uww1N/9mTR3zFSPtiwF/6vsUjxT0Wqza3qRNZmqRTQ970E4GiOzxjjg2ldxtYfmG4whTRBXcw93xVQ9TuKCEt9tGK7FX4HAWPQiVZ7HWL551Z6cwAnTJK9j8sUzHTCOpNyEFaisa4axu3pV1hVas5wbiNsigKQ+G8ZPE/3VOwMcY5oPSqRLpj06xHt9BHRoSylRPdrD12Qiwly5jQhJHzFm0Al+2jbNFCekdD6GHyB7yUa7bVc/o=

before_deploy:
  - export GEOTRELLIS_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: geotrellis/geotrellis
      branch: master
      jdk: oraclejdk7
      scala: "2.10.4"

  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: geotrellis/geotrellis
      branch: master
      jdk: oraclejdk7
      scala: "2.11.5"

after_deploy:
  - rm -f "${HOME}/.bintray/.credentials"
