---
- include: setup-master.yml
- include: setup-workers.yml

- name: Master Accumulo
  hosts: master
  roles: 
    - accumulo

  gather_facts: False

- name: Workers Accumulo
  hosts: workers
  roles: 
    - accumulo

  gather_facts: False