---

- name: Master
  hosts: master
  vars:
    hadoop_namenode: "{{ hostvars['master']['ansible_eth1']['ipv4']['address'] }}"
  roles:
    - common
    - hadoop

- name: Workers
  hosts: workers
  vars:
    hadoop_namenode: "{{ hostvars['master']['ansible_eth1']['ipv4']['address'] }}"
  roles:
    - common
    - hadoop