---

#Main tasks for hadoop master


- apt: name=hadoop-hdfs state=present force=yes
  sudo: yes

- name: Upload Hadoop config
  template: src=conf/{{ item }} dest=/etc/hadoop/conf
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - hadoop-env.sh
    - log4j.properties
  sudo: yes