---

#Main tasks for hadoop namenode
- apt: name=hadoop-hdfs-namenode state=present
  sudo: yes

- file: path=/var/hadoop-hdfs/namenode owner=hdfs group=hadoop mode=0755 state=directory
  sudo: yes

- name: Format the Namenode
  shell: hdfs namenode -format creates=/var/hadoop-hdfs/namenode/current
  sudo_user: hdfs 
  sudo: yes

# This entry messes up the Hadoop interface binding, causing it to bind to the local interface
- lineinfile:
    dest="/etc/hosts"
    regexp="^127.0.1.1"
    line=""
  sudo: yes
  notify: Restart Hadoop Namenode
  when: '"development" in group_names'

- service: name=hadoop-hdfs-namenode state=started enabled=yes
  sudo: yes